//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Boolean p_vRIF_InteractUI;
        
        private static SteamVR_Action_Boolean p_vRIF_Teleport;
        
        private static SteamVR_Action_Boolean p_vRIF_GrabPinch;
        
        private static SteamVR_Action_Boolean p_vRIF_GrabGrip;
        
        private static SteamVR_Action_Pose p_vRIF_Pose;
        
        private static SteamVR_Action_Skeleton p_vRIF_SkeletonLeftHand;
        
        private static SteamVR_Action_Skeleton p_vRIF_SkeletonRightHand;
        
        private static SteamVR_Action_Single p_vRIF_Squeeze;
        
        private static SteamVR_Action_Boolean p_vRIF_HeadsetOnHead;
        
        private static SteamVR_Action_Boolean p_vRIF_SnapTurnLeft;
        
        private static SteamVR_Action_Boolean p_vRIF_SnapTurnRight;
        
        private static SteamVR_Action_Vibration p_vRIF_Haptic;
        
        public static SteamVR_Action_Boolean vRIF_InteractUI
        {
            get
            {
                return SteamVR_Actions.p_vRIF_InteractUI.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean vRIF_Teleport
        {
            get
            {
                return SteamVR_Actions.p_vRIF_Teleport.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean vRIF_GrabPinch
        {
            get
            {
                return SteamVR_Actions.p_vRIF_GrabPinch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean vRIF_GrabGrip
        {
            get
            {
                return SteamVR_Actions.p_vRIF_GrabGrip.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose vRIF_Pose
        {
            get
            {
                return SteamVR_Actions.p_vRIF_Pose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Skeleton vRIF_SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.p_vRIF_SkeletonLeftHand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Skeleton vRIF_SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.p_vRIF_SkeletonRightHand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Single vRIF_Squeeze
        {
            get
            {
                return SteamVR_Actions.p_vRIF_Squeeze.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean vRIF_HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.p_vRIF_HeadsetOnHead.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean vRIF_SnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.p_vRIF_SnapTurnLeft.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean vRIF_SnapTurnRight
        {
            get
            {
                return SteamVR_Actions.p_vRIF_SnapTurnRight.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vibration vRIF_Haptic
        {
            get
            {
                return SteamVR_Actions.p_vRIF_Haptic.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.vRIF_InteractUI,
                    SteamVR_Actions.vRIF_Teleport,
                    SteamVR_Actions.vRIF_GrabPinch,
                    SteamVR_Actions.vRIF_GrabGrip,
                    SteamVR_Actions.vRIF_Pose,
                    SteamVR_Actions.vRIF_SkeletonLeftHand,
                    SteamVR_Actions.vRIF_SkeletonRightHand,
                    SteamVR_Actions.vRIF_Squeeze,
                    SteamVR_Actions.vRIF_HeadsetOnHead,
                    SteamVR_Actions.vRIF_SnapTurnLeft,
                    SteamVR_Actions.vRIF_SnapTurnRight,
                    SteamVR_Actions.vRIF_Haptic};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.vRIF_InteractUI,
                    SteamVR_Actions.vRIF_Teleport,
                    SteamVR_Actions.vRIF_GrabPinch,
                    SteamVR_Actions.vRIF_GrabGrip,
                    SteamVR_Actions.vRIF_Pose,
                    SteamVR_Actions.vRIF_SkeletonLeftHand,
                    SteamVR_Actions.vRIF_SkeletonRightHand,
                    SteamVR_Actions.vRIF_Squeeze,
                    SteamVR_Actions.vRIF_HeadsetOnHead,
                    SteamVR_Actions.vRIF_SnapTurnLeft,
                    SteamVR_Actions.vRIF_SnapTurnRight};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[] {
                    SteamVR_Actions.vRIF_Haptic};
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[] {
                    SteamVR_Actions.vRIF_Haptic};
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.vRIF_Pose};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.vRIF_InteractUI,
                    SteamVR_Actions.vRIF_Teleport,
                    SteamVR_Actions.vRIF_GrabPinch,
                    SteamVR_Actions.vRIF_GrabGrip,
                    SteamVR_Actions.vRIF_HeadsetOnHead,
                    SteamVR_Actions.vRIF_SnapTurnLeft,
                    SteamVR_Actions.vRIF_SnapTurnRight};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[] {
                    SteamVR_Actions.vRIF_Squeeze};
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[0];
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[] {
                    SteamVR_Actions.vRIF_SkeletonLeftHand,
                    SteamVR_Actions.vRIF_SkeletonRightHand};
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.vRIF_InteractUI,
                    SteamVR_Actions.vRIF_Teleport,
                    SteamVR_Actions.vRIF_GrabPinch,
                    SteamVR_Actions.vRIF_GrabGrip,
                    SteamVR_Actions.vRIF_Squeeze,
                    SteamVR_Actions.vRIF_HeadsetOnHead,
                    SteamVR_Actions.vRIF_SnapTurnLeft,
                    SteamVR_Actions.vRIF_SnapTurnRight};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_vRIF_InteractUI = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/VRIF/in/InteractUI")));
            SteamVR_Actions.p_vRIF_Teleport = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/VRIF/in/Teleport")));
            SteamVR_Actions.p_vRIF_GrabPinch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/VRIF/in/GrabPinch")));
            SteamVR_Actions.p_vRIF_GrabGrip = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/VRIF/in/GrabGrip")));
            SteamVR_Actions.p_vRIF_Pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/VRIF/in/Pose")));
            SteamVR_Actions.p_vRIF_SkeletonLeftHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/VRIF/in/SkeletonLeftHand")));
            SteamVR_Actions.p_vRIF_SkeletonRightHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/VRIF/in/SkeletonRightHand")));
            SteamVR_Actions.p_vRIF_Squeeze = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/VRIF/in/Squeeze")));
            SteamVR_Actions.p_vRIF_HeadsetOnHead = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/VRIF/in/HeadsetOnHead")));
            SteamVR_Actions.p_vRIF_SnapTurnLeft = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/VRIF/in/SnapTurnLeft")));
            SteamVR_Actions.p_vRIF_SnapTurnRight = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/VRIF/in/SnapTurnRight")));
            SteamVR_Actions.p_vRIF_Haptic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/VRIF/out/Haptic")));
        }
    }
}
